### Comprobar que la API vive
GET http://localhost:3000/

####################
##  REPARACIONES  ##
####################

### 1. Obtener todas las reparaciones (GET)
GET http://localhost:3000/api/reparaciones

### 2. Crear una nueva reparación (POST)
POST http://localhost:3000/api/reparaciones
Content-Type: application/json

{
  "fecha": "2026-03-30T10:00:00Z",
  "descripcion": "Cambio de aceite",
  "taller_nombre": "Talleres Paco",
  "kilometraje_momento": 286000,
  "vehiculoMatricula": "1234CCC"
}

### 3. Actualizar una reparación (PUT)
PUT http://localhost:3000/api/reparaciones/22
Content-Type: application/json

{
  "kilometraje_momento": 110000,
  "descripcion": "Cambio de pastillas, aceite y filtros nuevos"
}

### 4. Eliminar una reparación (DELETE)
DELETE http://localhost:3000/api/reparaciones/27

### 5. Buscar el historial de un coche por matrícula (GET)
GET http://localhost:3000/api/reparaciones/vehiculo/1234CCC

####################
##  PRESUPUESTOS  ##
####################

### 1. Ver todos los presupuestos con su reparación (GET)
GET http://localhost:3000/api/presupuestos

### 2. Crear un presupuesto automatizado (POST)
POST http://localhost:3000/api/presupuestos
Content-Type: application/json

{
  "base_imponible": 400.00,
  "reparacionId": 29
}

### 3. Actualizar un presupuesto (PUT)
PUT http://localhost:3000/api/presupuestos/9
Content-Type: application/json

{
  "base_imponible": 300.00
}

### 4. Eliminar un presupuesto (DELETE)
DELETE http://localhost:3000/api/presupuestos/12

### 5. Subir PDF a un presupuesto (Multipart Form)
POST http://localhost:3000/api/presupuestos/16/pdf
Content-Type: multipart/form-data; boundary=MiLimiteDeArchivo

--MiLimiteDeArchivo
Content-Disposition: form-data; name="archivo"; filename="prueba.pdf"
Content-Type: application/pdf

< holiwisssssssssssssss
--MiLimiteDeArchivo--

####################
## IDENTIDAD (JOSE) ##
####################

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb3NlQG9wZW5ob29kLmNvbSIsImlhdCI6MTc3NzM2MzI5MiwiZXhwIjoxNzc3NDQ5NjkyfQ.9x5qutZnj4_GYhRgm2MYJTbIU8T8QrR8EfN-U6M6nLg

### 1. Registrar un nuevo usuario (POST)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nombre": "josete98",
  "email": "jose@openhood.com",
  "telefono": "600123456",
  "password": "1234"
}

### Login de usuario (EJECUTA ESTE PRIMERO)
# @name login 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "jose@openhood.com",
  "password": "1234"
}

### Obtener mis vehículos
GET http://localhost:3000/api/vehiculos
Authorization: Bearer {{login.response.body.token}}

### Crear un vehículo
POST http://localhost:3000/api/vehiculos
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "matricula": "7788KFC",
  "marca": "Seat",
  "modelo": "Ibiza",
  "año": 2018,
  "kilometraje": 85000
}

### Listar todos mis coches
GET http://localhost:3000/api/vehiculos
Authorization: Bearer {{login.response.body.token}}

### Ver un coche específico 
GET http://localhost:3000/api/vehiculos/7784KFC
Authorization: Bearer {{login.response.body.token}}

### Borrar un coche
DELETE http://localhost:3000/api/vehiculos/7788KFC
Authorization: Bearer {{login.response.body.token}}

### Probar el UPDATE (Actualizar kilometraje y modelo)
PUT http://localhost:3000/api/vehiculos/7788KFC
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "kilometraje": 95000,
  "modelo": "Ibiza FR"
}